### ISSUE TITLE
Support TRC10 tokens in abi#encode

### ISSUE THREAD

**Issue by Kondax** [tronprotocol/tron-web#158]
Should implement the encoding equivalent for https://github.com/tronprotocol/tron-web/pull/152

Currently fails with

```js
{ Error: invalid type (arg="type", value="trcToken", version=4.0.20)
    at Object.throwError (E:\xxx\node_modules\ethers\errors.js:76:17)
    at getParamCoder (E:\xxx\node_modules\ethers\utils\abi-coder.js:906:12)
    at AbiCoder.<anonymous> (E:\xxx\node_modules\ethers\utils\abi-coder.js:939:25)
    at Array.forEach (<anonymous>)
    at AbiCoder.encode (E:\xxx\node_modules\ethers\utils\abi-coder.js:928:15)
    at e.value (E:\xxx\node_modules\tronweb\dist\TronWeb.node.js:1:27851)
    at E:\xxx\node_modules\tronweb\dist\TronWeb.node.js:1:14831
    at new Promise (<anonymous>)
    at Object.injectPromise (E:\xxx\node_modules\tronweb\dist\TronWeb.node.js:1:14803)
    at e.injectPromise (E:\xxx\node_modules\tronweb\dist\TronWeb.node.js:1:15050)
  reason: 'invalid type',
  code: 'INVALID_ARGUMENT',
  arg: 'type',
  value: 'trcToken' }```
```

@sullof an alternative solution I suggest is to change the `trcToken` type to `uint256` in the Contract types object. This won't fix it for people manually calling triggerSmartContract, but we should ideally have a forked abi encoder in the future for this.

**Comment by Kondax** [comment]
Also, another solution could be to push `uint256` instead of `trcToken` at

https://github.com/sullof/tron-web/blob/f86c62fc6fdd39017a1b6aeb31e6871b283c96ed/src/lib/transactionBuilder.js#L517

**Comment by sullof** [comment]
I am not sure that works. I am studying the problem.

**Comment by sullof** [comment]
@Kondax Can you provide me with an example that I can replicate?
