### ISSUE TITLE
Cannot find module 'TronWeb' when deployed Heroku (Linux machine)

### ISSUE THREAD

**Issue by kolya182** [tronprotocol/tron-web#56]
Deploying to Heroku (Linux) which is case sensitive caused this error. Have no any issue on macOS. Do you have any issue with it ?
```js
const TronWeb = require("TronWeb")
```
Fix:
```js
const TronWeb = require("tronweb")
```

Error stack
```json
2018-10-24T03:04:29.079389+00:00 app[web.1]: Error: Cannot find module 'TronWeb'
2018-10-24T03:04:29.079391+00:00 app[web.1]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
2018-10-24T03:04:29.079392+00:00 app[web.1]:     at Function.Module._load (internal/modules/cjs/loader.js:506:25)
2018-10-24T03:04:29.079394+00:00 app[web.1]:     at Module.require (internal/modules/cjs/loader.js:636:17)
2018-10-24T03:04:29.079396+00:00 app[web.1]:     at require (internal/modules/cjs/helpers.js:20:18)
2018-10-24T03:04:29.079398+00:00 app[web.1]:     at Object.<anonymous> (/app/dist/controllers/Tron/Tron.js:12:17)
2018-10-24T03:04:29.079403+00:00 app[web.1]:     at Module._compile (internal/modules/cjs/loader.js:688:30)
2018-10-24T03:04:29.079404+00:00 app[web.1]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
2018-10-24T03:04:29.079406+00:00 app[web.1]:     at Module.load (internal/modules/cjs/loader.js:598:32)
2018-10-24T03:04:29.079407+00:00 app[web.1]:     at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
2018-10-24T03:04:29.079409+00:00 app[web.1]:     at Function.Module._load (internal/modules/cjs/loader.js:529:3)
2018-10-24T03:04:29.079410+00:00 app[web.1]:     at Module.require (internal/modules/cjs/loader.js:636:17)
2018-10-24T03:04:29.079412+00:00 app[web.1]:     at require (internal/modules/cjs/helpers.js:20:18)
2018-10-24T03:04:29.079414+00:00 app[web.1]:     at Object.<anonymous> (/app/dist/routes/ApiRoutes.js:16:16)
2018-10-24T03:04:29.079415+00:00 app[web.1]:     at Module._compile (internal/modules/cjs/loader.js:688:30)
2018-10-24T03:04:29.079417+00:00 app[web.1]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
2018-10-24T03:04:29.079418+00:00 app[web.1]:     at Module.load (internal/modules/cjs/loader.js:598:32)
2018-10-24T03:04:29.079420+00:00 app[web.1]:     at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
2018-10-24T03:04:29.079421+00:00 app[web.1]:     at Function.Module._load (internal/modules/cjs/loader.js:529:3)
2018-10-24T03:04:29.079423+00:00 app[web.1]:     at Module.require (internal/modules/cjs/loader.js:636:17)
2018-10-24T03:04:29.079424+00:00 app[web.1]:     at require (internal/modules/cjs/helpers.js:20:18)
2018-10-24T03:04:29.079426+00:00 app[web.1]:     at Object.<anonymous> (/app/dist/App.js:16:21)
2018-10-24T03:04:29.079427+00:00 app[web.1]:     at Module._compile (internal/modules/cjs/loader.js:688:30)
2018-10-24T03:04:29.079429+00:00 app[web.1]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
2018-10-24T03:04:29.079430+00:00 app[web.1]:     at Module.load (internal/modules/cjs/loader.js:598:32)
2018-10-24T03:04:29.079432+00:00 app[web.1]:     at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
2018-10-24T03:04:29.079433+00:00 app[web.1]:     at Function.Module._load (internal/modules/cjs/loader.js:529:3)
2018-10-24T03:04:29.079435+00:00 app[web.1]:     at Module.require (internal/modules/cjs/loader.js:636:17)
2018-10-24T03:04:29.079436+00:00 app[web.1]:     at require (internal/modules/cjs/helpers.js:20:18)
2018-10-24T03:04:29.079438+00:00 app[web.1]:     at Object.<anonymous> (/app/dist/Server.js:3:15)
2018-10-24T03:04:29.079440+00:00 app[web.1]:     at Module._compile (internal/modules/cjs/loader.js:688:30)
2018-10-24T03:04:29.079441+00:00 app[web.1]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
2018-10-24T03:04:29.079443+00:00 app[web.1]:     at Module.load (internal/modules/cjs/loader.js:598:32)
2018-10-24T03:04:29.079444+00:00 app[web.1]:     at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
2018-10-24T03:04:29.079446+00:00 app[web.1]:     at Function.Module._load (internal/modules/cjs/loader.js:529:3)
```

**Comment by Kondax** [comment]
Are you running the demo? Or is this an import you're doing yourself? @kookiekrak this will need a documentation fix.

**Comment by kookiekrak** [comment]
@kolya182 we'll do a pass on the docs and fix the casing. Thanks for reporting!
