### ISSUE TITLE
getBase58CheckAddressFromPriKeyBase64String not working

### ISSUE THREAD

**Issue by mohit-lala** [tronprotocol/tron-web#99]
ReferenceError: _keyStr is not defined
    at C.decodeToByteArray (/home/hp/Projects/argowallet/node_modules/tronweb/dist/TronWeb.node.js:1:5916)
    at re (/home/hp/Projects/argowallet/node_modules/tronweb/dist/TronWeb.node.js:1:9306)
    at Module.Se (/home/hp/Projects/argowallet/node_modules/tronweb/dist/TronWeb.node.js:1:12218)
    at mPas.compareMasterPwd (/home/hp/Projects/argowallet/controllers/crypto/tron.js:501:52)
    at /home/hp/Projects/argowallet/controllers/mPwd.js:28:40
    at /home/hp/Projects/argowallet/node_modules/mongoose/lib/model.js:4499:16
    at model.$__save.error (/home/hp/Projects/argowallet/node_modules/mongoose/lib/model.js:404:7)
    at /home/hp/Projects/argowallet/node_modules/kareem/index.js:315:21
    at next (/home/hp/Projects/argowallet/node_modules/kareem/index.js:209:27)
    at /home/hp/Projects/argowallet/node_modules/kareem/index.js:182:9
    at process.nextTick (/home/hp/Projects/argowallet/node_modules/kareem/index.js:499:38)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)

showing this error

**Comment by Kondax** [comment]
Can you provide an example of how this is being caused?

**Comment by sullof** [comment]
https://github.com/tronprotocol/tron-web/pull/100
